### ISSUE TITLE
运行XuperClientTest中的setUp方法报错

### ISSUE THREAD

**Issue by wangqian0628** [xuperchain/xuper-java-sdk#1]
org.junit.internal.AssumptionViolatedException: got: <java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Workspaces/JavaWorkspace/xuper-java-sdk-master/target/test-classes/com/baidu/xuperunion/api/keys\private.key>, expected: null

	at org.junit.Assume.assumeThat(Assume.java:95)
	at org.junit.Assume.assumeNoException(Assume.java:142)
	at com.baidu.xuperunion.api.XuperClientTest.setUp(XuperClientTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Workspaces/JavaWorkspace/xuper-java-sdk-master/target/test-classes/com/baidu/xuperunion/api/keys\private.key
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.baidu.xuperunion.api.Account.create(Account.java:29)
	at com.baidu.xuperunion.api.XuperClientTest.setUp(XuperClientTest.java:29)
	... 23 more

**Comment by icexin** [comment]
看着像windows下路径的问题

**Comment by wangqian0628** [comment]
好像不是路径的问题，是private.key文件中的那个字符串中有特殊符号“：”导致的

**Comment by icexin** [comment]
这个测试在mac下和linux下是没有问题的，我找个windows的机器回归一下。

**Comment by wangqian0628** [comment]
好的，谢谢！
