### ISSUE TITLE
开放网络的测试网无法进行合约部署

### ISSUE THREAD

**Issue by zhangjiehang** [xuperchain/xuper-java-sdk#32]
使用的提供的Counter合约，但是一直报签名错误
`Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN: Err:500-50400-verify tx failed+err:Txid verify failed
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at com.baidu.xuper.pb.XchainGrpc$XchainBlockingStub.postTx(XchainGrpc.java:1622)
	at com.baidu.xuper.api.Transaction.send(Transaction.java:487)
	at com.baidu.xuper.api.XuperClient.invokeContract(XuperClient.java:114)
	at com.baidu.xuper.api.XuperClient.deployEVMContract(XuperClient.java:342)
	at com.fingerchar.api.web.FcExternalUserController.deployTestContract(FcExternalUserController.java:404)
	at com.fingerchar.api.web.FcExternalUserController.main(FcExternalUserController.java:484)`

**Comment by uaanaa** [comment]
SDK 使用的什么版本的？

**Comment by zhangjiehang** [comment]
> SDK 使用的什么版本的？

<dependency>
		<groupId>com.baidu.xuper</groupId>
		<artifactId>xuper-java-sdk</artifactId>
		<version>0.2.0</version>
</dependency>

**Comment by uaanaa** [comment]
可以提供一下代码片段或加入超级链官方微信群获取支持

**Comment by zhangjiehang** [comment]
> 可以提供一下代码片段或加入超级链官方微信群获取支持

IntegrationToken.abi
`[{"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"symbol","type":"string"},{"internalType":"uint256","name":"totalSupply","type":"uint256"}],"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType":"address","name":"spender","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"inputs":[],"name":"addCount","outputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"spender","type":"address"}],"name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnFrom","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"recoveryAddress","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"recovery","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}]`

IntegrationToken.bin
`6080604052604051620026a4380380620026a48339818101604052810190620000299190620003ae565b828281600390805190602001906200004392919062000275565b5080600490805190602001906200005c92919062000275565b50505033600560006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550620000e9600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16670de0b6b3a764000083620000dd91906200059d565b620000f260201b60201c565b5050506200071b565b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16141562000165576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016200015c9062000489565b60405180910390fd5b62000179600083836200026b60201b60201c565b80600260008282546200018d919062000540565b92505081905550806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254620001e4919062000540565b925050819055508173ffffffffffffffffffffffffffffffffffffffff16600073ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040516200024b9190620004ab565b60405180910390a362000267600083836200027060201b60201c565b5050565b505050565b505050565b82805462000283906200063e565b90600052602060002090601f016020900481019282620002a75760008555620002f3565b82601f10620002c257805160ff1916838001178555620002f3565b82800160010185558215620002f3579182015b82811115620002f2578251825591602001919060010190620002d5565b5b50905062000302919062000306565b5090565b5b808211156200032157600081600090555060010162000307565b5090565b60006200033c6200033684620004fc565b620004c8565b9050828152602081018484840111156200035557600080fd5b6200036284828562000608565b509392505050565b600082601f8301126200037c57600080fd5b81516200038e84826020860162000325565b91505092915050565b600081519050620003a88162000701565b92915050565b600080600060608486031215620003c457600080fd5b600084015167ffffffffffffffff811115620003df57600080fd5b620003ed868287016200036a565b935050602084015167ffffffffffffffff8111156200040b57600080fd5b62000419868287016200036a565b92505060406200042c8682870162000397565b9150509250925092565b600062000445601f836200052f565b91507f45524332303a206d696e7420746f20746865207a65726f2061646472657373006000830152602082019050919050565b6200048381620005fe565b82525050565b60006020820190508181036000830152620004a48162000436565b9050919050565b6000602082019050620004c2600083018462000478565b92915050565b6000604051905081810181811067ffffffffffffffff82111715620004f257620004f1620006d2565b5b8060405250919050565b600067ffffffffffffffff8211156200051a5762000519620006d2565b5b601f19601f8301169050602081019050919050565b600082825260208201905092915050565b60006200054d82620005fe565b91506200055a83620005fe565b9250827fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0382111562000592576200059162000674565b5b828201905092915050565b6000620005aa82620005fe565b9150620005b783620005fe565b9250817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0483118215151615620005f357620005f262000674565b5b828202905092915050565b6000819050919050565b60005b83811015620006285780820151818401526020810190506200060b565b8381111562000638576000848401525b50505050565b600060028204905060018216806200065757607f821691505b602082108114156200066e576200066d620006a3565b5b50919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6200070c81620005fe565b81146200071857600080fd5b50565b611f79806200072b6000396000f3fe608060405234801561001057600080fd5b506004361061010b5760003560e01c80636cefce6e116100a257806395d89b411161007157806395d89b41146102ba578063a457c2d7146102d8578063a9059cbb14610308578063dd62ed3e14610338578063f2fde38b146103685761010b565b80636cefce6e1461023257806370a082311461025057806379cc6790146102805780638da5cb5b1461029c5761010b565b8063313ce567116100de578063313ce567146101ac57806339509351146101ca5780633fb0971b146101fa57806342966c68146102165761010b565b806306fdde0314610110578063095ea7b31461012e57806318160ddd1461015e57806323b872dd1461017c575b600080fd5b610118610384565b6040516101259190611a54565b60405180910390f35b610148600480360381019061014391906113bc565b610416565b6040516101559190611a39565b60405180910390f35b610166610434565b6040516101739190611c56565b60405180910390f35b6101966004803603810190610191919061136d565b61043e565b6040516101a39190611a39565b60405180910390f35b6101b4610536565b6040516101c19190611c71565b60405180910390f35b6101e460048036038101906101df91906113bc565b61053f565b6040516101f19190611a39565b60405180910390f35b610214600480360381019061020f91906113bc565b6105eb565b005b610230600480360381019061022b91906113f8565b6106f7565b005b61023a61070b565b6040516102479190611c56565b60405180910390f35b61026a60048036038101906102659190611308565b6107f7565b6040516102779190611c56565b60405180910390f35b61029a600480360381019061029591906113bc565b61083f565b005b6102a46108ba565b6040516102b19190611a1e565b60405180910390f35b6102c26108e0565b6040516102cf9190611a54565b60405180910390f35b6102f260048036038101906102ed91906113bc565b610972565b6040516102ff9190611a39565b60405180910390f35b610322600480360381019061031d91906113bc565b610a5d565b60405161032f9190611a39565b60405180910390f35b610352600480360381019061034d9190611331565b610a7b565b60405161035f9190611c56565b60405180910390f35b610382600480360381019061037d9190611308565b610b02565b005b60606003805461039390611e45565b80601f01602080910402602001604051908101604052809291908181526020018280546103bf90611e45565b801561040c5780601f106103e15761010080835404028352916020019161040c565b820191906000526020600020905b8154815290600101906020018083116103ef57829003601f168201915b5050505050905090565b600061042a610423610bd6565b8484610bde565b6001905092915050565b6000600254905090565b600061044b848484610da9565b6000600160008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000610496610bd6565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905082811015610516576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161050d90611b56565b60405180910390fd5b61052a85610522610bd6565b858403610bde565b60019150509392505050565b60006012905090565b60006105e161054c610bd6565b84846001600061055a610bd6565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020546105dc9190611ca8565b610bde565b6001905092915050565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161461067b576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161067290611c16565b60405180910390fd5b80610685836107f7565b10156106c6576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016106bd90611b96565b60405180910390fd5b6106f382600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1683610da9565b5050565b610708610702610bd6565b8261102a565b50565b60008061073c606461072e6005610720610434565b61120190919063ffffffff16565b61127c90919063ffffffff16565b90508061074f61074a610bd6565b6107f7565b1061078f576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161078690611b16565b60405180910390fd5b6107bd60646107af60016107a1610434565b61120190919063ffffffff16565b61127c90919063ffffffff16565b91506107f3600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff166107ed610bd6565b84610da9565b5090565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b60006108528361084d610bd6565b610a7b565b905081811015610897576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161088e90611b76565b60405180910390fd5b6108ab836108a3610bd6565b848403610bde565b6108b5838361102a565b505050565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6060600480546108ef90611e45565b80601f016020809104026020016040519081016040528092919081815260200182805461091b90611e45565b80156109685780601f1061093d57610100808354040283529160200191610968565b820191906000526020600020905b81548152906001019060200180831161094b57829003601f168201915b5050505050905090565b60008060016000610981610bd6565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905082811015610a3e576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610a3590611c36565b60405180910390fd5b610a52610a49610bd6565b85858403610bde565b600191505092915050565b6000610a71610a6a610bd6565b8484610da9565b6001905092915050565b6000600160008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905092915050565b600560009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610b92576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610b8990611c16565b60405180910390fd5b80600560006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600033905090565b600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff161415610c4e576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610c4590611bf6565b60405180910390fd5b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff161415610cbe576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610cb590611ab6565b60405180910390fd5b80600160008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508173ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b92583604051610d9c9190611c56565b60405180910390a3505050565b600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff161415610e19576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610e1090611bd6565b60405180910390fd5b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff161415610e89576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610e8090611a76565b60405180910390fd5b610e948383836112d4565b60008060008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905081811015610f1a576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610f1190611ad6565b60405180910390fd5b8181036000808673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550816000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254610fad9190611ca8565b925050819055508273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040516110119190611c56565b60405180910390a36110248484846112d9565b50505050565b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16141561109a576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161109190611bb6565b60405180910390fd5b6110a6826000836112d4565b60008060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205490508181101561112c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161112390611a96565b60405180910390fd5b8181036000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555081600260008282546111839190611d89565b92505081905550600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040516111e89190611c56565b60405180910390a36111fc836000846112d9565b505050565b6000808314156112145760009050611276565b600082846112229190611d2f565b90508284826112319190611cfe565b14611271576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161126890611b36565b60405180910390fd5b809150505b92915050565b60008082116112c0576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016112b790611af6565b60405180910390fd5b81836112cc9190611cfe565b905092915050565b505050565b505050565b6000813590506112ed81611f15565b92915050565b60008135905061130281611f2c565b92915050565b60006020828403121561131a57600080fd5b6000611328848285016112de565b91505092915050565b6000806040838503121561134457600080fd5b6000611352858286016112de565b9250506020611363858286016112de565b9150509250929050565b60008060006060848603121561138257600080fd5b6000611390868287016112de565b93505060206113a1868287016112de565b92505060406113b2868287016112f3565b9150509250925092565b600080604083850312156113cf57600080fd5b60006113dd858286016112de565b92505060206113ee858286016112f3565b9150509250929050565b60006020828403121561140a57600080fd5b6000611418848285016112f3565b91505092915050565b61142a81611dbd565b82525050565b61143981611dcf565b82525050565b600061144a82611c8c565b6114548185611c97565b9350611464818560208601611e12565b61146d81611f04565b840191505092915050565b6000611485602383611c97565b91507f45524332303a207472616e7366657220746f20746865207a65726f206164647260008301527f65737300000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b60006114eb602283611c97565b91507f45524332303a206275726e20616d6f756e7420657863656564732062616c616e60008301527f63650000000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b6000611551602283611c97565b91507f45524332303a20617070726f766520746f20746865207a65726f20616464726560008301527f73730000000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b60006115b7602683611c97565b91507f45524332303a207472616e7366657220616d6f756e742065786365656473206260008301527f616c616e636500000000000000000000000000000000000000000000000000006020830152604082019050919050565b600061161d601a83611c97565b91507f536166654d6174683a206469766973696f6e206279207a65726f0000000000006000830152602082019050919050565b600061165d602b83611c97565b91507f506f696e747320726561636820746865207570706572206c696d6974206f662060008301527f636f6c6c656374696f6e210000000000000000000000000000000000000000006020830152604082019050919050565b60006116c3602183611c97565b91507f536166654d6174683a206d756c7469706c69636174696f6e206f766572666c6f60008301527f77000000000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b6000611729602883611c97565b91507f45524332303a207472616e7366657220616d6f756e742065786365656473206160008301527f6c6c6f77616e63650000000000000000000000000000000000000000000000006020830152604082019050919050565b600061178f602483611c97565b91507f45524332303a206275726e20616d6f756e74206578636565647320616c6c6f7760008301527f616e6365000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b60006117f5601583611c97565b91507f496e73756666696369656e7420696e74656772616c00000000000000000000006000830152602082019050919050565b6000611835602183611c97565b91507f45524332303a206275726e2066726f6d20746865207a65726f2061646472657360008301527f73000000000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b600061189b602583611c97565b91507f45524332303a207472616e736665722066726f6d20746865207a65726f20616460008301527f64726573730000000000000000000000000000000000000000000000000000006020830152604082019050919050565b6000611901602483611c97565b91507f45524332303a20617070726f76652066726f6d20746865207a65726f2061646460008301527f72657373000000000000000000000000000000000000000000000000000000006020830152604082019050919050565b6000611967601a83611c97565b91507f63757272656e7420636f6e7472616365206e6f74206f776e65720000000000006000830152602082019050919050565b60006119a7602583611c97565b91507f45524332303a2064656372656173656420616c6c6f77616e63652062656c6f7760008301527f207a65726f0000000000000000000000000000000000000000000000000000006020830152604082019050919050565b611a0981611dfb565b82525050565b611a1881611e05565b82525050565b6000602082019050611a336000830184611421565b92915050565b6000602082019050611a4e6000830184611430565b92915050565b60006020820190508181036000830152611a6e818461143f565b905092915050565b60006020820190508181036000830152611a8f81611478565b9050919050565b60006020820190508181036000830152611aaf816114de565b9050919050565b60006020820190508181036000830152611acf81611544565b9050919050565b60006020820190508181036000830152611aef816115aa565b9050919050565b60006020820190508181036000830152611b0f81611610565b9050919050565b60006020820190508181036000830152611b2f81611650565b9050919050565b60006020820190508181036000830152611b4f816116b6565b9050919050565b60006020820190508181036000830152611b6f8161171c565b9050919050565b60006020820190508181036000830152611b8f81611782565b9050919050565b60006020820190508181036000830152611baf816117e8565b9050919050565b60006020820190508181036000830152611bcf81611828565b9050919050565b60006020820190508181036000830152611bef8161188e565b9050919050565b60006020820190508181036000830152611c0f816118f4565b9050919050565b60006020820190508181036000830152611c2f8161195a565b9050919050565b60006020820190508181036000830152611c4f8161199a565b9050919050565b6000602082019050611c6b6000830184611a00565b92915050565b6000602082019050611c866000830184611a0f565b92915050565b600081519050919050565b600082825260208201905092915050565b6000611cb382611dfb565b9150611cbe83611dfb565b9250827fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff03821115611cf357611cf2611e77565b5b828201905092915050565b6000611d0982611dfb565b9150611d1483611dfb565b925082611d2457611d23611ea6565b5b828204905092915050565b6000611d3a82611dfb565b9150611d4583611dfb565b9250817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0483118215151615611d7e57611d7d611e77565b5b828202905092915050565b6000611d9482611dfb565b9150611d9f83611dfb565b925082821015611db257611db1611e77565b5b828203905092915050565b6000611dc882611ddb565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b600060ff82169050919050565b60005b83811015611e30578082015181840152602081019050611e15565b83811115611e3f576000848401525b50505050565b60006002820490506001821680611e5d57607f821691505b60208210811415611e7157611e70611ed5565b5b50919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b6000601f19601f8301169050919050565b611f1e81611dbd565b8114611f2957600080fd5b50565b611f3581611dfb565b8114611f4057600080fd5b5056fea2646970667358221220385eba419576fc6a55f0d9b54a2f70c05cc471ba261cb2e9976b4bc8de335f9264736f6c63430008000033`

部署代码，基于SDK的 sdk.testnet.yaml
`Config.setConfigPath("./sdk.testnet.yaml");
  XuperClient client =  new XuperClient("14.215.179.74:37101");
 // 使用私有key
 final String privateKey ="xxxxxxx";
 Account account = Account.create(ECKeyPair.create(new BigInteger(privateKey)));
 account.setContractAccount("XC2051672461162186@xuper");
 String abi = "xxxx";
 String bin = "xxxx";
 String contractName = "texttokenfirst";
 Map<String, String> args = new HashMap<>();
 args.put("name", "test");
 args.put("symbol", "test");
 args.put("totalSupply", "1000");

 Transaction t = client.deployEVMContract(account, bin.getBytes(), abi.getBytes(), contractName, args);
 System.out.println("txID:" + t.getTxid());
`
智能合约是遵循ERC20所写的积分合约，在正式环境同样的代码是能正常运行的，但是在开放环境的测试网络是报签名错误的。

**Comment by zhangjiehang** [comment]
> 可以提供一下代码片段或加入超级链官方微信群获取支持

另外微信社群找不到

**Comment by uaanaa** [comment]
![image](https://user-images.githubusercontent.com/51440377/152636024-90dea494-7889-484d-b3d6-b47237dd7d9b.png)

**Comment by uaanaa** [comment]
你好，在 sdk.testnet.yaml  中， 增加字段 txVersion: 1   再看下

**Comment by zhangjiehang** [comment]
> 

不可以哦，报错，在0.2.0版本下，config中没有对应属性
`Caused by: Cannot create property=txVersion for JavaBean=com.baidu.xuper.config.Config@2a5c8d3f
 in 'reader', line 3, column 1:
    endorseServiceHost: "14.215.179. ... 
    ^
Unable to find property 'txVersion' on class: com.baidu.xuper.config.Config
 in 'reader', line 18, column 12:
    txVersion: 1
               ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
	at com.baidu.xuper.config.Config.getConfigFromYaml(Config.java:49)
	at com.baidu.xuper.config.Config.getInstance(Config.java:36)
	... 5 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'txVersion' on class: com.baidu.xuper.config.Config
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:159)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148)
	at org.yaml.snakeyaml.TypeDescription.discoverProperty(TypeDescription.java:246)
	at org.yaml.snakeyaml.TypeDescription.getProperty(TypeDescription.java:257)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:209)
	... 15 more`

**Comment by uaanaa** [comment]
你好，我确认了一下， java sdk 在测试环境部署合约确实存在问题，此问题后续会进行修复。
在正式开放网络（39.156.69.83:37100）以及本地搭建的xuperchain中，不会有此问题。
当前如果需要在开放测试网络（14.215.179.74:37101） 部署合约，可以优先采用 go sdk 或 在工作台页面直接创建部署。
