### ISSUE TITLE
Unable to get message info for com.baidu.xuper.pb.XchainOuterClass$AddressStatus

### ISSUE THREAD

**Issue by LKCoinOne** [xuperchain/xuper-java-sdk#42]
#### mysql-connector-java 8.0.X 跟 xuper-java-sdk 有冲突;

```java
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.29</version>
</dependency>
    
<dependency>
    <groupId>com.baidu.xuper</groupId>
    <artifactId>xuper-java-sdk</artifactId>
    <version>0.2.0</version>
</dependency>
```

#### 异常问题

```java
12:05:33.334 [pool-2-thread-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - [handleError,96] - Unexpected error occurred in scheduled task.
java.lang.ExceptionInInitializerError: null
	at com.baidu.xuper.api.XuperClient.getBalance(XuperClient.java:182)
	at com.blockchain.nft.project.chain.service.impl.ChainServiceImpl.getBalance(ChainServiceImpl.java:61)
	at com.blockchain.nft.project.chain.service.impl.ChainServiceImpl$$FastClassBySpringCGLIB$$a3a0b9a8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.blockchain.nft.project.chain.service.impl.ChainServiceImpl$$EnhancerBySpringCGLIB$$e6e63287.getBalance(<generated>)
	at com.blockchain.nft.project.chain.job.ChainNFTJob.upChainJop(ChainNFTJob.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get message info for com.baidu.xuper.pb.XchainOuterClass$AddressStatus
	at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:62)
	at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
	at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
	at com.baidu.xuper.pb.XchainOuterClass$AddressStatus.<clinit>(XchainOuterClass.java:9909)
	... 20 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at com.baidu.xuper.pb.XchainOuterClass$AddressStatus.dynamicMethod(XchainOuterClass.java:9900)
	at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:256)
	at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:286)
	at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
	... 26 common frames omitted
```

**Comment by LKCoinOne** [comment]
##### 目前解决方案：使用mysql-connector-java 5.1.9版本，既可以兼容mysql 8.0 的版本，没有query_cache_size的问题，又没有xupersdk冲突问题

```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.9</version>
</dependency>
```

**Comment by uaanaa** [comment]
好的，辛苦，我们后面看下
