### ISSUE TITLE
client调用报错

### ISSUE THREAD

**Issue by bobmax88** [xuperchain/xuper-java-sdk#45]
请问这是哪里设置的问题吗？调用client的任何方法都报这个错
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.baidu.xuper.pb.XchainOuterClass$Header.dynamicMethod(XchainOuterClass.java:1451)
	at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:336)
	at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:1514)
	at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:258)
	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:433)
	at com.baidu.xuper.api.Common.newHeader(Common.java:9)
	at com.baidu.xuper.api.XuperClient.getSystemStatus(XuperClient.java:291)

**Comment by uaanaa** [comment]
哪个版本的SDK？ 包含调用上下文的代码可以截图一下吗？

**Comment by bobmax88** [comment]
sdk版本0.2.0
![image](https://user-images.githubusercontent.com/106077715/169813787-250f2792-33d8-4159-b3b7-6fa8c26884e6.png)

**Comment by uaanaa** [comment]
是使用maven 集成的吗？

**Comment by uaanaa** [comment]
好的，看你的节点链接的是开放网络， 这个问题是必现的吗？ 是否有重试过？

**Comment by bobmax88** [comment]
是必现的，client的任何一个方法都报这个错误，我看配置文件应该也没什么问题，config里面的值我可以获取到

**Comment by uaanaa** [comment]
好的， 可以配置为 0.2.1 版本的SDK试下

**Comment by bobmax88** [comment]
引入依赖包之后不报错了，感谢感谢
